-- 1. Bank Statements Table
CREATE TABLE bank_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref TEXT UNIQUE,
    bank_name TEXT,
    amount NUMERIC,
    sender_name TEXT,
    transaction_time TIMESTAMPTZ,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Donations Table
CREATE TABLE donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_number TEXT,
    sender_name TEXT,
    amount NUMERIC,
    transaction_ref TEXT UNIQUE,
    bank_name TEXT,
    purpose TEXT,
    status TEXT DEFAULT 'processing',
    transaction_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Review Queue Table
CREATE TABLE review_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT REFERENCES donations (id),
    issue TEXT,
    status TEXT DEFAULT 'pending_review',
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);